"""
app.py
------------------------
Flask Real-Time Dashboard: Reads anomaly detection results from CSV,
displaying the traffic flow list and flagged anomaly alerts on a web page.

Future Extensions:
    - Implement true real-time push updates via Flask-SocketIO (currently re-reads the CSV on page refresh)
    - Integrate a database to replace CSV files and support historical queries

Usage:
    python app.py
    Then open http://127.0.0.1:5000 in your browser
"""

from flask import Flask, render_template
import pandas as pd
import os

app = Flask(__name__)

# Path to the anomaly detection results file (generated by model/predict.py)
RESULTS_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "flagged_anomalies.csv")


def load_results():
    if not os.path.exists(RESULTS_PATH):
        return pd.DataFrame()
    return pd.read_csv(RESULTS_PATH)


@app.route("/")
def dashboard():
    df = load_results()

    if df.empty:
        return render_template(
            "dashboard.html",
            total_flows=0,
            total_anomalies=0,
            anomalies=[],
        )

    anomalies_df = df[df["is_anomaly"] == True].sort_values("anomaly_score")

    return render_template(
        "dashboard.html",
        total_flows=len(df),
        total_anomalies=len(anomalies_df),
        anomalies=anomalies_df.to_dict(orient="records"),
    )


if __name__ == "__main__":
    app.run(debug=True)